import secrets
import logging
from datetime import datetime
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException, Request, Response, BackgroundTasks, status
import os
from fastapi.responses import RedirectResponse, FileResponse
from sqlmodel import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.exc import IntegrityError

from app.config import settings
from app.database import get_db_session, async_session
from app.id_gen import SnowflakeIDGenerator, encode_base62
from app.cache import get_cached_url, set_cached_url, invalidate_cached_url
from app.rate_limiter import rate_limiter
from app.models import (
    URL, URLShortenRequest, URLResponse, StatsResponse,
    APIKey, APIKeyCreateRequest, APIKeyResponse,
    User, UserRegisterRequest, UserLoginRequest, TokenResponse
)
from app.auth import (
    get_current_user_optional, get_current_user,
    get_password_hash, verify_password, create_access_token
)


logger = logging.getLogger(__name__)
router = APIRouter()

# Initialize Snowflake ID Generator
id_generator = SnowflakeIDGenerator(worker_id=settings.WORKER_ID)


@router.get("/", include_in_schema=False)
async def serve_home():
    """Serves the frontend single page app index.html."""
    static_file_path = os.path.join(os.path.dirname(__file__), "static", "index.html")
    return FileResponse(static_file_path)


# --- User Authentication & Dashboard Endpoints ---

@router.post("/auth/register", status_code=status.HTTP_201_CREATED)
async def register_user(
    body: UserRegisterRequest,
    db: AsyncSession = Depends(get_db_session)
):
    """Registers a new user account with a secure hashed password."""
    # Check if username is already taken
    statement = select(User).where(User.username == body.username)
    result = await db.execute(statement)
    existing_user = result.scalar_one_or_none()
    
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Username is already taken."
        )
        
    hashed_pwd = get_password_hash(body.password)
    user_record = User(username=body.username, hashed_password=hashed_pwd)
    
    db.add(user_record)
    await db.commit()
    
    return {"detail": "User registered successfully."}


@router.post("/auth/login", response_model=TokenResponse)
async def login_user(
    body: UserLoginRequest,
    db: AsyncSession = Depends(get_db_session)
):
    """Validates login credentials and returns a JWT access token."""
    statement = select(User).where(User.username == body.username)
    result = await db.execute(statement)
    user = result.scalar_one_or_none()
    
    if not user or not verify_password(body.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid username or password."
        )
        
    access_token = create_access_token(data={"sub": user.username})
    return TokenResponse(access_token=access_token, token_type="bearer")


@router.get("/auth/me")
async def get_me(current_user: User = Depends(get_current_user)):
    """Returns details of the currently authenticated user."""
    return {
        "username": current_user.username,
        "created_at": current_user.created_at
    }


@router.get("/my-urls")
async def get_my_urls(
    request: Request,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db_session)
):
    """Returns all short URLs generated by the currently logged-in user."""
    statement = select(URL).where(URL.user_id == current_user.id).order_by(URL.created_at.desc())
    result = await db.execute(statement)
    urls = result.scalars().all()
    
    # Respect proxy/load balancer header for URL scheme
    scheme = request.headers.get("x-forwarded-proto", "https")
    base_url = str(request.base_url)
    if base_url.startswith("http://") and scheme == "https":
        base_url = base_url.replace("http://", "https://", 1)
        
    return [
        {
            "id": str(u.id),
            "short_code": u.short_code,
            "short_url": f"{base_url}{u.short_code}",
            "long_url": u.long_url,
            "created_at": u.created_at,
            "click_count": u.click_count
        } for u in urls
    ]


async def increment_click_count_bg(short_code: str):
    """
    Background task to increment click count in Postgres.
    We create a fresh database session inside the task to ensure it doesn't
    interfere with the request's session lifecycle.
    """
    async with async_session() as session:
        try:
            statement = select(URL).where(URL.short_code == short_code)
            result = await session.execute(statement)
            url_record = result.scalar_one_or_none()
            if url_record:
                url_record.click_count += 1
                await session.commit()
        except Exception as e:
            logger.error("Failed to increment click count for %s: %s", short_code, str(e))


@router.post(
    "/shorten",
    response_model=URLResponse,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(rate_limiter.check_rate_limit)]
)
async def shorten_url(
    request: Request,
    body: URLShortenRequest,
    db: AsyncSession = Depends(get_db_session),
    current_user: Optional[User] = Depends(get_current_user_optional)
):
    """
    Shorten a URL. Generates a custom Snowflake ID, encodes to Base62,
    and stores in PostgreSQL. Caches result in Redis.
    """
    long_url_str = str(body.url)
    max_retries = 3
    
    for attempt in range(max_retries):
        try:
            # Generate custom Snowflake ID
            snowflake_id = id_generator.generate()
            # Encode ID into Base62
            short_code = encode_base62(snowflake_id)
            
            url_record = URL(
                id=snowflake_id,
                short_code=short_code,
                long_url=long_url_str,
                created_at=datetime.utcnow(),
                user_id=current_user.id if current_user else None
            )
            
            db.add(url_record)
            await db.commit()
            await db.refresh(url_record)
            
            # Cache the newly created URL mapping in Redis
            await set_cached_url(short_code, long_url_str)
            
            # Construct absolute short URL, respecting reverse proxy headers for HTTPS
            scheme = request.headers.get("x-forwarded-proto", "https")
            base_url = str(request.base_url)
            if base_url.startswith("http://") and scheme == "https":
                base_url = base_url.replace("http://", "https://", 1)
            short_url = f"{base_url}{short_code}"
            
            return URLResponse(
                short_code=short_code,
                short_url=short_url,
                long_url=long_url_str,
                created_at=url_record.created_at,
                click_count=url_record.click_count
            )
            
        except IntegrityError:
            await db.rollback()
            logger.warning("Collision detected for Snowflake ID. Retrying ID generation.")
            if attempt == max_retries - 1:
                raise HTTPException(
                    status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                    detail="Failed to generate a unique short URL after multiple attempts."
                )


@router.get(
    "/{code}",
    dependencies=[Depends(rate_limiter.check_rate_limit)]
)
async def redirect_url(
    code: str,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db_session)
):
    """
    Redirect a short URL code to its original long URL.
    Implements Redis caching to bypass Postgres on cache hit.
    Updates stats asynchronously using FastAPI background tasks.
    """
    # 1. Try fetching from Redis cache
    long_url = await get_cached_url(code)
    
    if not long_url:
        # 2. Cache Miss: Query PostgreSQL
        statement = select(URL).where(URL.short_code == code)
        result = await db.execute(statement)
        url_record = result.scalar_one_or_none()
        
        if not url_record:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Short URL not found."
            )
            
        long_url = url_record.long_url
        # 3. Populate Redis Cache
        await set_cached_url(code, long_url)
        
    # 4. Schedule click count increment in background
    background_tasks.add_task(increment_click_count_bg, code)
    
    # 5. Return HTTP 302 (Found) to ensure subsequent requests bypass client browser cache
    # to maintain accurate click metrics.
    return RedirectResponse(url=long_url, status_code=status.HTTP_302_FOUND)


@router.get(
    "/stats/{code}",
    response_model=StatsResponse,
    dependencies=[Depends(rate_limiter.check_rate_limit)]
)
async def get_url_stats(
    code: str,
    db: AsyncSession = Depends(get_db_session)
):
    """
    Retrieves click statistics and creation metadata for a short URL.
    """
    statement = select(URL).where(URL.short_code == code)
    result = await db.execute(statement)
    url_record = result.scalar_one_or_none()
    
    if not url_record:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Short URL not found."
        )
        
    return StatsResponse(
        short_code=url_record.short_code,
        long_url=url_record.long_url,
        created_at=url_record.created_at,
        click_count=url_record.click_count
    )


@router.post(
    "/keys",
    response_model=APIKeyResponse,
    status_code=status.HTTP_201_CREATED
)
async def generate_api_key(
    body: APIKeyCreateRequest,
    db: AsyncSession = Depends(get_db_session)
):
    """
    Generates a secure API key with customizable rate limits.
    """
    raw_key = secrets.token_urlsafe(32)
    api_key_record = APIKey(
        key=raw_key,
        client_name=body.client_name,
        created_at=datetime.utcnow(),
        rate_limit_capacity=body.rate_limit_capacity,
        rate_limit_refill_rate=body.rate_limit_refill_rate
    )
    
    db.add(api_key_record)
    await db.commit()
    await db.refresh(api_key_record)
    
    return APIKeyResponse(
        key=raw_key,
        client_name=api_key_record.client_name,
        rate_limit_capacity=api_key_record.rate_limit_capacity or settings.DEFAULT_RATE_LIMIT_CAPACITY,
        rate_limit_refill_rate=api_key_record.rate_limit_refill_rate or settings.DEFAULT_RATE_LIMIT_REFILL_RATE
    )


@router.delete(
    "/{code}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(rate_limiter.check_rate_limit)]
)
async def delete_url(
    code: str,
    db: AsyncSession = Depends(get_db_session)
):
    """
    Deletes a short URL. Invalidates the Redis cache entry to prevent stale reads (cache invalidation).
    """
    statement = select(URL).where(URL.short_code == code)
    result = await db.execute(statement)
    url_record = result.scalar_one_or_none()
    
    if not url_record:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Short URL not found."
        )
        
    await db.delete(url_record)
    await db.commit()
    
    # Cache Invalidation: immediately purge from Redis cache
    await invalidate_cached_url(code)
    
    return Response(status_code=status.HTTP_204_NO_CONTENT)


